Use relative path to locate EditorInstance.json
Unity-Technologies/vscode-unity-debug pull request #174
Opened 2020-07-30 21:56 UTC by terrehbyte

This fulfills the issue marked as an enhancement in #118.

This breaks any workspaces that don't have the Unity project directory as the workspace folder, but given that the default Unity workflow expects such, I'd imagine that's OK.

2020-09-11 10:59 UTC, MihaPro-CarX approved these changes

2020-09-11 12:31 UTC, miniwolf commented
What is the issue with having the absolute path?
We want to avoid ambiguity, users having multiple folders in the workspace. Wouldn't this remove support for that workflow?

2020-09-11 18:37 UTC, terrehbyte commented
How do you envision having multiple folders in the workspace?

By default, the workspace that Unity generates is placed at the root of the Unity project. If users wanted to have multiple Unity projects open, then they'd create a multi-root workspace and add the other project's workspace. Each workspace, when "launched", resolve `${workspaceFolder}` differently and correctly. (If they don't adopt a multi-root workspace, then I can see how this would break things -- would we be interested in supporting an option to do either or?)

The only notable benefit to referencing the workspace path would be allowing teams to include their `.vscode/` folder via version control in case the team wanted to synchronize their settings/launch-settings/etc.

2020-11-11 22:50 UTC, TCROC commented
This is a nice enhancement.  @terrehbyte How would it break things if they don't adopt a multi-root workspace?  Doesn't ${workspaceFolder} resolve to the absolute path anyways?  This would simply add more flexibility.  Including allowing the debugger to keep functioning even if users move their project to a different directory.  And as you suggested, you could include the .vscode/ in the repo now as well.

2020-11-12 23:35 UTC, miniwolf requested changes
Thank you for your contribution. If you can fix the indentation, so that it is consistent. Then I will be happy to merge this in.

2021-02-16 05:50 UTC, otri commented
@miniwolf   Why is this held up?  This is super helpful for sharing a project that involves multiple Unity instances running, this is a really helpful improvement.  Can we not merge and fix line indent along the way?

2021-02-16 06:16 UTC, terrehbyte commented
Sorry for the delay on such a small change (and thanks for @otri for bubbling this to the top of my inbox).

The indentation for that specific change should be tabs now in alignment with the lines surrounding it.

> This is a nice enhancement. @terrehbyte How would it break things if they don't adopt a multi-root workspace? Doesn't ${workspaceFolder} resolve to the absolute path anyways? This would simply add more flexibility. Including allowing the debugger to keep functioning even if users move their project to a different directory. And as you suggested, you could include the .vscode/ in the repo now as well.

@TCROC, indeed, I believe it does resolve to the absolute path after evaluation. I'd imagine everything would continue to work as expected as long as the workspace folder that's opened is the root folder for the Unity project. Anything else, and the relative `/Library/EditorInstance.json` path won't work, but someone would have to go out of their way to do that (and could manually fix the path in that case). 😋

2021-02-16 08:03 UTC, miniwolf approved these changes

2021-02-16 08:03 UTC, merged